"""Stage 02 — Local generation pipeline.

Reads datasets from datasets/02_preprocessed and produces matching
*.jsonl files in datasets/03_local_generated by querying a local
inference server (see request_example.py for the request shape).
"""

from __future__ import annotations

import json
import logging
import time
import urllib.error
import urllib.request
from http.client import RemoteDisconnected
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

from config import (
    PREPROCESSED_DATA_DIR,
    LOCAL_GENERATED_DATA_DIR,
    LOCAL_INFER_URL,
    LOCAL_GENERATION_LOG_PATH,
)

# --- proxy safety: never proxy localhost ---
_proxy_handler = urllib.request.ProxyHandler({})
_opener = urllib.request.build_opener(_proxy_handler)
urllib.request.install_opener(_opener)
# ------------------------------------------


def _build_logger() -> logging.Logger:
    """Creates a dedicated logger for local generation errors."""
    logger = logging.getLogger("local_generation")
    if logger.handlers:
        return logger

    log_path = Path(LOCAL_GENERATION_LOG_PATH)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    handler = logging.FileHandler(log_path, mode="a", encoding="utf-8")
    formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
    handler.setFormatter(formatter)

    logger.setLevel(logging.WARNING)
    logger.addHandler(handler)
    logger.propagate = False
    return logger


logger = _build_logger()


def load_processed_ids(output_path: Path) -> Set[str]:
    """Scans an existing jsonl file and returns already processed sentence_ids."""
    processed_ids: Set[str] = set()
    if not output_path.exists():
        return processed_ids

    with open(output_path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            sentence_id = record.get("sentence_id")
            if sentence_id:
                processed_ids.add(sentence_id)
    return processed_ids


def iter_preprocessed_sentences(filepath: Path) -> Iterable[Dict[str, Any]]:
    """Yields sentence records from a preprocessed *.json file."""
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    for item in data:
        if isinstance(item, dict):
            yield item


def _extract_nodes(response_json: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """Best-effort extraction of the nodes list from the server response."""
    nodes = response_json.get("nodes")
    if isinstance(nodes, list):
        return nodes  # type: ignore[return-value]

    # Some servers wrap the payload; handle a few common shapes safely.
    payload = response_json.get("json")
    if isinstance(payload, dict) and isinstance(payload.get("nodes"), list):
        return payload.get("nodes")  # type: ignore[return-value]

    if isinstance(payload, list):
        return payload  # type: ignore[return-value]

    return None


def request_inference(
    sentence_data: Dict[str, Any], *, retries: int = 3, backoff_sec: float = 1.0
) -> Tuple[Optional[List[Dict[str, Any]]], Optional[str]]:
    """Sends a local inference request and returns (nodes, error_message)."""
    try:
        payload_text = json.dumps(sentence_data, ensure_ascii=False)
    except (TypeError, ValueError) as exc:
        return None, f"payload_build_failed: {exc}"

    text = sentence_data.get("text", "")
    payload = json.dumps({"text": text}, ensure_ascii=False).encode("utf-8")
    last_error: Exception | None = None

    for attempt in range(1, retries + 1):
        req = urllib.request.Request(
            LOCAL_INFER_URL,
            data=payload,
            headers={"Content-Type": "application/json; charset=utf-8"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=300) as resp:
                body = resp.read().decode("utf-8")
            response_json = json.loads(body)
            nodes = _extract_nodes(response_json)
            if nodes is None:
                return None, "nodes_missing_in_response"
            return nodes, None
        except RemoteDisconnected as exc:
            last_error = exc
        except urllib.error.HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            last_error = RuntimeError(f"http_{exc.code}: {exc.reason}; body={error_body}")
        except urllib.error.URLError as exc:
            last_error = exc
        except json.JSONDecodeError as exc:
            last_error = RuntimeError(f"response_json_decode_failed: {exc}")

        if attempt < retries:
            time.sleep(backoff_sec * attempt)

    assert last_error is not None
    return None, str(last_error)


def _log_node_mismatch(sentence_id: str, expected: int, actual: int) -> None:
    logger.warning(
        "NODE_COUNT_MISMATCH: sentence_id=%s expected=%s actual=%s",
        sentence_id,
        expected,
        actual,
    )


def _log_request_error(sentence_id: str, error_text: str) -> None:
    logger.warning("REQUEST_ERROR: sentence_id=%s error=%s", sentence_id, error_text)


def process_file(preprocessed_path: Path, output_path: Path) -> None:
    """Processes one preprocessed split into a jsonl output file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    processed_ids = load_processed_ids(output_path)

    print(f"\n--- Local generation: {preprocessed_path.name} -> {output_path.name} ---")
    if processed_ids:
        print(f"Пропускаю уже обработанные записи: {len(processed_ids)}")

    total = 0
    written = 0
    errors = 0

    with open(output_path, "a", encoding="utf-8") as f_out:
        for sentence_data in iter_preprocessed_sentences(preprocessed_path):
            total += 1
            sentence_id = sentence_data.get("sentence_id")
            if not sentence_id or sentence_id in processed_ids:
                continue

            text = sentence_data.get("text", "")
            expected_nodes_len = len(sentence_data.get("nodes", []))

            nodes, error_text = request_inference(sentence_data)

            node_error = False
            if error_text is not None:
                node_error = True
                errors += 1
                _log_request_error(sentence_id, error_text)
                nodes = nodes or []

            actual_nodes_len = len(nodes)
            if actual_nodes_len != expected_nodes_len:
                node_error = True
                errors += 1
                _log_node_mismatch(sentence_id, expected_nodes_len, actual_nodes_len)

            record = {
                "sentence_id": sentence_id,
                "text": text,
                "nodes": nodes,
                "node_error": node_error,
            }
            f_out.write(json.dumps(record, ensure_ascii=False) + "\n")
            written += 1

    print(f"Всего предложений: {total}")
    print(f"Новых записей добавлено: {written}")
    if errors:
        print(f"Предупреждений/ошибок: {errors} (см. {LOCAL_GENERATION_LOG_PATH})")


def run_pipeline() -> None:
    """Runs local generation for all preprocessed *.json files."""
    files_to_process = sorted(PREPROCESSED_DATA_DIR.glob("*.json"))
    if not files_to_process:
        print(f"❌ В {PREPROCESSED_DATA_DIR} не найдено *.json файлов.")
        return

    print("=== Stage 02: Local generation ===")
    print(f"Сервер инференса: {LOCAL_INFER_URL}")

    for preprocessed_path in files_to_process:
        output_filename = preprocessed_path.name.replace(".json", ".jsonl")
        output_path = LOCAL_GENERATED_DATA_DIR / output_filename
        process_file(preprocessed_path, output_path)

    print("\n✅ Local generation завершена.")


if __name__ == "__main__":
    run_pipeline()
