from __future__ import annotations


DEFAULT_GOOGLE_MODEL_NAME = "gemma-4-31b-it"
DEFAULT_LOCAL_MODEL_NAME = "local_http"
DEFAULT_LOCAL_API_URL = "http://127.0.0.1:8080/generate"
DEFAULT_GOOGLE_API_KEYS_STR = ""
DEFAULT_GOOGLE_SCHEDULER_KEYS_STR = ""
DEFAULT_GOOGLE_THINKING_LEVEL = "HIGH"
DEFAULT_GOOGLE_ENABLE_SEARCH_TOOL = False
DEFAULT_MAX_OUTPUT_TOKENS = 32760
DEFAULT_TEMPERATURE = 0.0
DEFAULT_GENERATION_PROFILE = "standard"
